### PR TITLE
Upgrade to Ember 1.10

### PR DESCRIPTION
**Pull request by nummi**
:boom: :boom: :boom:

Before this is merged and deployed:
https://github.com/Tahi-project/tahi-plos-authors-card needs the `ember-1-10` branch merged and deployed as well.

:boom: :boom: :boom:

### CODE REVIEW

**Comment by mikem** [comment]
This PR removes the style guide template. Is that intentional, or perhaps a bad merge? Does this branch still have a style guide?

**Comment by nummi** [comment]
Ooops. I didn't want to check that in. The styleguide template is causing HTMLBars compilation errors right now.

**Comment by rizwanreza** [comment]
:+1: Looking good, merge when green.

**Comment by rizwanreza** [comment]
```
not ok 113 Firefox 34.0 - integration/serializer: extractMany puts normalizes things via their 'type' attribute
    ---
        actual: >
            null
        message: >
            Died on test #1 test@http://localhost:7357/assets/test-support.js:1693:5
            @http://localhost:7357/assets/tahi.js:58034:3
            requireModule@http://localhost:7357/assets/vendor.js:79:16
            TestLoader.prototype.require@http://localhost:7357/assets/test-loader.js:29:9
            TestLoader.prototype.loadModules@http://localhost:7357/assets/test-loader.js:21:13
            TestLoader.load@http://localhost:7357/assets/test-loader.js:36:7
            @http://localhost:7357/assets/test-support.js:5294:5
            : No model was found for 'invitation'
        Log: >
    ...
```

**Comment by mikem** [comment]
I merged the `ember-1-10` branch into master in Tahi-project/tahi-plos-authors-card. I guess this means should update the `package.json` entry for this card to use `master` instead of the SHA it currently has? /c @tonywok @nummi

**Comment by nummi** [comment]
Yup
